<a href="https://colab.research.google.com/github/vohoangtien290905/Thuc-Hanh-DeepLearning/blob/main/Lab_1/Lab1_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import numpy as np
import pandas as pd
#tạo array 1 - chiều

#tạo list
my_list = [1,2,3,4,5]
print(my_list)

#chuyển list -> numpy array
my_numpy_array = np.array(my_list)
print(my_numpy_array)

#Cách 2
a = np.array([1,2,3,4,5])
print(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 2 3 4 5]

In [7]:
c = np.array([(1, 2, 3),
              (4, 5, 6)
            ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

### Tạo mảng NumPy bằng các hàm chuyên dụng

Ngoài việc tạo mảng từ danh sách Python, NumPy cung cấp nhiều hàm tiện lợi để tạo mảng với các giá trị cụ thể:

*   **`np.zeros(shape)`**: Tạo một mảng chứa toàn số 0.
*   **`np.ones(shape)`**: Tạo một mảng chứa toàn số 1.
*   **`np.arange(start, stop, step)`**: Tạo một mảng với các giá trị cách đều trong một khoảng đã cho.
*   **`np.linspace(start, stop, num)`**: Tạo một mảng với một số lượng giá trị được phân bố đều trong một khoảng đã cho.

In [ ]:
# Tạo mảng chứa toàn số 0 (zeros array)
zeros_array = np.zeros((3, 4)) # Mảng 3 hàng, 4 cột toàn số 0
print("Mảng zeros:\n", zeros_array)

# Tạo mảng chứa toàn số 1 (ones array)
ones_array = np.ones(5) # Mảng 1 chiều với 5 phần tử toàn số 1
print("\nMảng ones:\n", ones_array)

# Tạo mảng với các giá trị cách đều (arange)
# Từ 0 đến dưới 10, bước nhảy 2
arange_array = np.arange(0, 10, 2)
print("\nMảng arange:\n", arange_array)

# Tạo mảng với các giá trị được phân bố đều (linspace)
# 5 điểm nằm đều giữa 0 và 1 (bao gồm cả 0 và 1)
linspace_array = np.linspace(0, 1, 5)
print("\nMảng linspace:\n", linspace_array)

### Phép toán số học cơ bản

NumPy cho phép thực hiện các phép toán số học trên toàn bộ mảng một cách hiệu quả, áp dụng phép toán theo từng phần tử.

In [8]:
# Tạo hai mảng ví dụ
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

# Phép cộng (element-wise)
sum_array = a1 + a2
print(f"Cộng: {a1} + {a2} = {sum_array}")

# Phép trừ (element-wise)
diff_array = a2 - a1
print(f"Trừ: {a2} - {a1} = {diff_array}")

# Phép nhân (element-wise)
prod_array = a1 * a2
print(f"Nhân: {a1} * {a2} = {prod_array}")

# Phép chia (element-wise)
div_array = a2 / a1
print(f"Chia: {a2} / {a1} = {div_array}")

# Phép toán với một số vô hướng (scalar)
scalar_mult = a1 * 2
print(f"Nhân với số vô hướng: {a1} * 2 = {scalar_mult}")

Cộng: [1 2 3] + [4 5 6] = [5 7 9]
Trừ: [4 5 6] - [1 2 3] = [3 3 3]
Nhân: [1 2 3] * [4 5 6] = [ 4 10 18]
Chia: [4 5 6] / [1 2 3] = [4.  2.5 2. ]
Nhân với số vô hướng: [1 2 3] * 2 = [2 4 6]

In [9]:
# Mảng 1 chiều
my_array_1d = np.array([10, 20, 30, 40, 50])
print(f"Mảng 1 chiều: {my_array_1d}")

# Truy cập phần tử đơn
print(f"Phần tử đầu tiên: {my_array_1d[0]}")
print(f"Phần tử cuối cùng: {my_array_1d[-1]}\n")

# Cắt lát (Slicing)
print(f"Cắt lát từ vị trí 1 đến 3 (không bao gồm 3): {my_array_1d[1:3]}")
print(f"Cắt lát từ đầu đến vị trí 3: {my_array_1d[:3]}")
print(f"Cắt lát từ vị trí 2 đến cuối: {my_array_1d[2:]}")
print(f"Cắt lát tất cả phần tử: {my_array_1d[:]}")
print(f"Cắt lát với bước nhảy: {my_array_1d[::2]}\n")

# Mảng 2 chiều
my_array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Mảng 2 chiều:\n{my_array_2d}")

# Truy cập phần tử (hàng, cột)
print(f"Phần tử tại hàng 0, cột 1: {my_array_2d[0, 1]}") # Tương đương my_array_2d[0][1]
print(f"Phần tử tại hàng 2, cột 0: {my_array_2d[2, 0]}\n")

# Cắt lát hàng
print(f"Hàng đầu tiên: {my_array_2d[0, :]}")
print(f"Các hàng từ 1 đến hết: {my_array_2d[1:, :]}\n")

# Cắt lát cột
print(f"Cột thứ hai: {my_array_2d[:, 1]}")
print(f"Các cột từ 0 đến 2 (không bao gồm 2): {my_array_2d[:, :2]}\n")

# Cắt lát phức tạp (chọn một vùng)
print(f"Vùng con (hàng 0-1, cột 0-1):\n{my_array_2d[0:2, 0:2]}")

Mảng 1 chiều: [10 20 30 40 50]
Phần tử đầu tiên: 10
Phần tử cuối cùng: 50

Cắt lát từ vị trí 1 đến 3 (không bao gồm 3): [20 30]
Cắt lát từ đầu đến vị trí 3: [10 20 30]
Cắt lát từ vị trí 2 đến cuối: [30 40 50]
Cắt lát tất cả phần tử: [10 20 30 40 50]
Cắt lát với bước nhảy: [10 30 50]

Mảng 2 chiều:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Phần tử tại hàng 0, cột 1: 2
Phần tử tại hàng 2, cột 0: 7

Hàng đầu tiên: [1 2 3]
Các hàng từ 1 đến hết: [[4 5 6]
 [7 8 9]]

Cột thứ hai: [2 5 8]
Các cột từ 0 đến 2 (không bao gồm 2): [[1 2]
 [4 5]
 [7 8]]

Vùng con (hàng 0-1, cột 0-1):
[[1 2]
 [4 5]]

In [10]:
import pandas as pd

# Tạo một DataFrame từ dictionary
data = {
    'Tên': ['Alice', 'Bob', 'Charlie', 'David'],
    'Tuổi': [24, 27, 22, 32],
    'Thành phố': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

print("DataFrame đã tạo:")
display(df.head())

DataFrame đã tạo:

       Tên  Tuổi    Thành phố
0    Alice    24     New York
1      Bob    27  Los Angeles
2  Charlie    22      Chicago
3    David    32      Houston

In [11]:
print("Kích thước DataFrame (số hàng, số cột):", df.shape)

print("\nThông tin DataFrame:")
df.info()

print("\nThống kê mô tả DataFrame:")
display(df.describe(include='all')) # include='all' để bao gồm cả cột object (chuỗi)

Kích thước DataFrame (số hàng, số cột): (4, 3)

Thông tin DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Tên        4 non-null      object
 1   Tuổi       4 non-null      int64
 2   Thành phố  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Thống kê mô tả DataFrame:

          Tên       Tuổi Thành phố
count       4   4.000000         4
unique      4        NaN         4
top     Alice        NaN  New York
freq        1        NaN         1
mean      NaN  26.250000       NaN
std       NaN   4.349329       NaN
min       NaN  22.000000       NaN
25%       NaN  23.500000       NaN
50%       NaN  25.500000       NaN
75%       NaN  28.250000       NaN
max       NaN  32.000000       NaN

In [12]:
# Chọn một cột
print("\nCột 'Tên':")
display(df['Tên'])

# Chọn nhiều cột
print("\nCác cột 'Tên' và 'Tuổi':")
display(df[['Tên', 'Tuổi']])

# Chọn hàng theo vị trí (hàng đầu tiên)
print("\nHàng đầu tiên (sử dụng iloc):")
display(df.iloc[0])

# Chọn nhiều hàng theo vị trí (hàng 0 đến hàng 1)
print("\nHàng 0 đến hàng 1 (sử dụng iloc):")
display(df.iloc[0:2])

# Chọn hàng và cột cụ thể theo vị trí
print("\nPhần tử tại hàng 1, cột 0 (sử dụng iloc):")
print(df.iloc[1, 0])

Cột 'Tên':

0      Alice
1        Bob
2    Charlie
3      David
Name: Tên, dtype: object

Các cột 'Tên' và 'Tuổi':

       Tên  Tuổi
0    Alice    24
1      Bob    27
2  Charlie    22
3    David    32

Hàng đầu tiên (sử dụng iloc):

Tên             Alice
Tuổi               24
Thành phố    New York
Name: 0, dtype: object

Hàng 0 đến hàng 1 (sử dụng iloc):

     Tên  Tuổi    Thành phố
0  Alice    24     New York
1    Bob    27  Los Angeles

Phần tử tại hàng 1, cột 0 (sử dụng iloc):
Bob

### Bài tập NumPy: Tạo mảng ngẫu nhiên và kiểm tra giá trị

**Yêu cầu:**
1.  Tạo một mảng NumPy 2 chiều kích thước 3x3 chứa 9 số nguyên ngẫu nhiên trong khoảng từ 0 đến 20 (bao gồm cả 0 và 20).
2.  Kiểm tra xem tất cả các phần tử trong mảng vừa tạo có khác 0 hay không bằng cách sử dụng hàm `np.all()`.

In [13]:
# 1. Tạo mảng 2 chiều 3x3 với số nguyên ngẫu nhiên trong khoảng [0, 20]
random_array_3x3 = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên 3x3:\n", random_array_3x3)

# 2. Kiểm tra tất cả các phần tử trong mảng khác 0
all_non_zero = np.all(random_array_3x3 != 0)
print(f"\nTất cả các phần tử trong mảng có khác 0 không? {all_non_zero}")

Mảng ngẫu nhiên 3x3:
 [[ 6  6  6]
 [ 9  9  3]
 [17  7  8]]

Tất cả các phần tử trong mảng có khác 0 không? True

In [14]:
print("--- So sánh mảng 1 chiều ---")
# Tạo hai mảng 1 chiều
arr_1d_a = np.array([10, 20, 30, 40])
arr_1d_b = np.array([15, 20, 25, 35])

print(f"Mảng A (1D): {arr_1d_a}")
print(f"Mảng B (1D): {arr_1d_b}\n")

# So sánh greater
result_greater_1d = np.greater(arr_1d_a, arr_1d_b)
print(f"arr_1d_a > arr_1d_b: {result_greater_1d}")

# So sánh greater_equal
result_greater_equal_1d = np.greater_equal(arr_1d_a, arr_1d_b)
print(f"arr_1d_a >= arr_1d_b: {result_greater_equal_1d}")

# So sánh less
result_less_1d = np.less(arr_1d_a, arr_1d_b)
print(f"arr_1d_a < arr_1d_b: {result_less_1d}")

# So sánh less_equal
result_less_equal_1d = np.less_equal(arr_1d_a, arr_1d_b)
print(f"arr_1d_a <= arr_1d_b: {result_less_equal_1d}")

--- So sánh mảng 1 chiều ---
Mảng A (1D): [10 20 30 40]
Mảng B (1D): [15 20 25 35]

arr_1d_a > arr_1d_b: [False False  True  True]
arr_1d_a >= arr_1d_b: [False  True  True  True]
arr_1d_a < arr_1d_b: [ True False False False]
arr_1d_a <= arr_1d_b: [ True  True False False]

In [15]:
print("\n--- So sánh mảng 2 chiều ---")
# Tạo hai mảng 2 chiều
arr_2d_a = np.array([[1, 5, 3],
                     [7, 2, 9]])
arr_2d_b = np.array([[2, 4, 3],
                     [6, 2, 10]])

print(f"Mảng A (2D):\n{arr_2d_a}")
print(f"Mảng B (2D):\n{arr_2d_b}\n")

# So sánh greater
result_greater_2d = np.greater(arr_2d_a, arr_2d_b)
print(f"arr_2d_a > arr_2d_b:\n{result_greater_2d}")

# So sánh greater_equal
result_greater_equal_2d = np.greater_equal(arr_2d_a, arr_2d_b)
print(f"arr_2d_a >= arr_2d_b:\n{result_greater_equal_2d}")

# So sánh less
result_less_2d = np.less(arr_2d_a, arr_2d_b)
print(f"arr_2d_a < arr_2d_b:\n{result_less_2d}")

# So sánh less_equal
result_less_equal_2d = np.less_equal(arr_2d_a, arr_2d_b)
print(f"arr_2d_a <= arr_2d_b:\n{result_less_equal_2d}")

--- So sánh mảng 2 chiều ---
Mảng A (2D):
[[1 5 3]
 [7 2 9]]
Mảng B (2D):
[[ 2  4  3]
 [ 6  2 10]]

arr_2d_a > arr_2d_b:
[[False  True False]
 [ True False False]]
arr_2d_a >= arr_2d_b:
[[False  True  True]
 [ True  True False]]
arr_2d_a < arr_2d_b:
[[ True False False]
 [False False  True]]
arr_2d_a <= arr_2d_b:
[[ True False  True]
 [False  True  True]]

In [16]:
# Tạo mảng gồm 10 số 1
ones_array = np.ones(10, dtype=int)
print(f"Mảng 10 số 1: {ones_array}")

# Tạo mảng gồm 10 số 0
zeros_array = np.zeros(10, dtype=int)
print(f"Mảng 10 số 0: {zeros_array}")

# Tạo mảng gồm 10 số 5
fives_array = np.full(10, 5, dtype=int)
print(f"Mảng 10 số 5: {fives_array}")

# Ghép nối các mảng lại với nhau
combined_array = np.concatenate((ones_array, zeros_array, fives_array))
print(f"\nMảng kết hợp (10 số 1, 10 số 0, 10 số 5):\n{combined_array}")
print(f"Tổng số phần tử trong mảng kết hợp: {combined_array.size}")

Mảng 10 số 1: [1 1 1 1 1 1 1 1 1 1]
Mảng 10 số 0: [0 0 0 0 0 0 0 0 0 0]
Mảng 10 số 5: [5 5 5 5 5 5 5 5 5 5]

Mảng kết hợp (10 số 1, 10 số 0, 10 số 5):
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]
Tổng số phần tử trong mảng kết hợp: 30

In [17]:
# Tạo ma trận đơn vị 3x3
identity_matrix_3x3 = np.identity(3, dtype=int)
print("Ma trận đơn vị 3x3:\n", identity_matrix_3x3)

# Bạn cũng có thể tạo ma trận đơn vị bằng np.eye()
# np.eye(N, M=None, k=0, dtype=<class 'float'>)
# Với N là số hàng, M là số cột (nếu bỏ qua sẽ mặc định bằng N)
# k là chỉ số của đường chéo (0 là đường chéo chính, dương là trên, âm là dưới)
identity_matrix_with_eye = np.eye(3, dtype=int)
print("\nMa trận đơn vị 3x3 (sử dụng np.eye()):\n", identity_matrix_with_eye)

Ma trận đơn vị 3x3:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

Ma trận đơn vị 3x3 (sử dụng np.eye()):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

In [18]:
# Tạo hai Series Pandas
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 10])

print(f"Series 1:\n{series1}")
print(f"\nSeries 2:\n{series2}")

# Phép cộng
sum_series = series1 + series2
print(f"\nKết quả phép cộng:\n{sum_series}")

# Phép trừ
diff_series = series1 - series2
print(f"\nKết quả phép trừ:\n{diff_series}")

# Phép nhân
prod_series = series1 * series2
print(f"\nKết quả phép nhân:\n{prod_series}")

# Phép chia
div_series = series1 / series2
print(f"\nKết quả phép chia:\n{div_series}")

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
0     1
1     3
2     5
3     7
4    10
dtype: int64

Kết quả phép cộng:
0     3
1     7
2    11
3    15
4    20
dtype: int64

Kết quả phép trừ:
0    1
1    1
2    1
3    1
4    0
dtype: int64

Kết quả phép nhân:
0      2
1     12
2     30
3     56
4    100
dtype: int64

Kết quả phép chia:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

### Thay đổi Index của Pandas Series với `reindex()`

`reindex()` là một phương thức quan trọng trong Pandas giúp bạn thay đổi (hoặc căn chỉnh lại) index của Series hoặc DataFrame. Nếu một nhãn mới không có trong index gốc, giá trị tương ứng sẽ là `NaN` (Not a Number) theo mặc định.

In [19]:
# Tạo một Series mẫu
original_series = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series gốc:\n", original_series)

# Định nghĩa một index mới
new_index = ['a', 'e', 'c', 'f']

# Sử dụng reindex để thay đổi index
reindexed_series = original_series.reindex(new_index)
print("\nSeries sau khi reindex:\n", reindexed_series)

# Ví dụ với fill_value
new_index_with_fill = ['a', 'g', 'c', 'h']
reindexed_series_fill = original_series.reindex(new_index_with_fill, fill_value=0)
print("\nSeries sau khi reindex với fill_value=0:\n", reindexed_series_fill)

Series gốc:
 a    10
b    20
c    30
d    40
dtype: int64

Series sau khi reindex:
 a    10.0
e     NaN
c    30.0
f     NaN
dtype: float64

Series sau khi reindex với fill_value=0:
 a    10
g     0
c    30
h     0
dtype: int64